# Generated by Django 4.2.1 on 2023-05-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('charge', 'CHARGE'), ('transfer', 'TRANSFER')], max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destination_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_seller', to=settings.AUTH_USER_MODEL)),
                ('source_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
